In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#GroupBy

In [ ]:
data = {
'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
'Date': pd.date_range('2023-01-01', periods= 8)
}

df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
df.groupby('Store')['Quantity'].sum()

Store
S1    58
S2    65
Name: Quantity, dtype: int64

In [ ]:
df.groupby('Category')['Sales'].sum()
#Groupby columns

          Sales  Quantity
Category
A           570        45
B           930        78

In [ ]:
df.groupby(['Category','Store'])[['Sales','Quantity']].sum()
#Groupby multi columns

                Sales  Quantity
Category Store
A        S1       220        18
         S2       350        27
B        S1       500        40
         S2       430        38

In [ ]:
#Aggregation

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
df['Sales'].mean()

np.float64(187.5)

In [ ]:
###-Mean,Max,Min,Median-###

In [ ]:
df['Sales'].median()

190.0

In [ ]:
df['Sales'].agg(['mean', 'max', 'min', 'median'])

mean      187.5
max       300.0
min       100.0
median    190.0
Name: Sales, dtype: float64

In [ ]:
#Pivot tables

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
'Date': pd.date_range('2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
           'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
'Sales': np. random. randint(100, 1000, 20),
'Units': np.random.randint(10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df ['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    145     13   John  January      Q1
1  2023-01-02       B   West    581     31   Mary  January      Q1
2  2023-01-03       C  North    442     54    Bob  January      Q1
3  2023-01-04       D  South    653     34  Alice  January      Q1
4  2023-01-05       A   East    472     31   John  January      Q1
5  2023-01-06       B   West    457     41   Mary  January      Q1
6  2023-01-07       C  North    897     47    Bob  January      Q1
7  2023-01-08       D  South    363     54  Alice  January      Q1
8  2023-01-09       A   East    163     10   John  January      Q1
9  2023-01-10       B   West    656     83   Mary  January      Q1
10 2023-01-11       C  North    623     30    Bob  January      Q1
11 2023-01-12       D  South    621     79  Alice  January      Q1
12 2023-01-13       A   East    351     80   John  January      Q1
13 2023-01-14       B   West    592     32   Mary  January      Q1
14 2023-01-15       C  North    929     85    Bob  January      Q1
15 2023-01-16       D  South    640     75  Alice  January      Q1
16 2023-01-17       A   East    820     57   John  January      Q1
17 2023-01-18       B   West    837     17   Mary  January      Q1
18 2023-01-19       C  North    797     79    Bob  January      Q1
19 2023-01-20       D  South    862     56  Alice  January      Q1

In [ ]:
pivot2= pd.pivot_table(df, values= 'Units', index= 'Region', columns= 'Product')
pivot2

Product     A     B     C     D
Region
East     38.2   NaN   NaN   NaN
North     NaN   NaN  59.0   NaN
South     NaN   NaN   NaN  59.6
West      NaN  40.8   NaN   NaN

In [ ]:
pivot2= pd.pivot_table(df, values= 'Sales', index= 'Product', columns= 'Region')
pivot2

Region    East  North  South   West
Product
A        390.2    NaN    NaN    NaN
B          NaN    NaN    NaN  624.6
C          NaN  737.6    NaN    NaN
D          NaN    NaN  627.8    NaN

In [ ]:
values= {'East': 10, 'South': 30}
pivot2= pd.pivot_table(df, values= 'Sales', index= 'Product', columns= 'Region')
pivot2 = pivot2.fillna(values)
pivot2

Region    East  North  South   West
Product
A        390.2    NaN   30.0    NaN
B         10.0    NaN   30.0  624.6
C         10.0  737.6   30.0    NaN
D         10.0    NaN  627.8    NaN

In [ ]:
#Cross tabs

In [ ]:
pivot2= pd.pivot_table(df, values= 'Sales', index= 'Region', columns= 'Product')
pivot2

Product      A      B      C      D
Region
East     390.2    NaN    NaN    NaN
North      NaN    NaN  737.6    NaN
South      NaN    NaN    NaN  627.8
West       NaN  624.6    NaN    NaN

In [ ]:
#use Cross tabs for counting purpose

In [ ]:
pd.crosstab(df['Region'], df['Product'])    #for counting purpose

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0