In [ ]:
import numpy as np
import pandas as pd

In [ ]:
labels = ['a' ,'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1:10, 2:20, 3:30}

In [ ]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(my_list, index= labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
d

{1: 10, 2: 20, 3: 30}

In [ ]:
pd.Series(d, index=labels)

a   NaN
b   NaN
c   NaN
dtype: float64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
#Dataframes in Pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#creating a dataframes

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62880, 85000]
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62880
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2= pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
column = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns= column)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#selection and indexing of columns

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [ ]:
df[['Name', 'Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62880
3  Linda   85000

In [ ]:
df2["Designation"] = ["Doctor", "Eng.", "Pilot", "Driver"]
df2        #creating a new column

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000       Pilot
3  Linda   42    London   85000      Driver

In [ ]:
df2.drop('Designation', axis= 1, inplace= True)
#completely delete column

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop(0, axis= 0)       #delete columns

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [ ]:
df2.drop(['Age','City'], axis= 1)

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc[[0,1]]    #selecting rows

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df2.loc[[1,2],['Age','City']]

   Age    City
1   34   Paris
2   29  Berlin

In [ ]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [ ]:
#conditions section

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df2[(df2['Age'] > 30) & (df2["City"] =='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000